apiVersion: v1
kind: Pod
metadata:
  name: linuxpod
  namespace: demok8s
spec:
  containers:
    - name: busybox
      image: busybox
      command: 
        - sleep
        - "3600" # sleep for 1 hour
      resources:
        requests:
          memory: "64Mi" # 64Mi = 64 * 1024 * 1024 bytes
          cpu: "250m" # 250m = 250 millicpu = 0.25 cpu
        limits:
          memory: "128Mi" # 128Mi = 128 * 1024 * 1024 bytes
          cpu: "500m" # 500m = 500 millicpu = 0.5 cpu
    - name: aline
      image: alpine
      command: 
        - sleep
        - "3600" # sleep for 1 hour
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"