apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-mongodb
  labels:
    app: mongo
  namespace: demok8s
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: mern-mongodb
  template:
    metadata:
      name: mern-mongodb
      labels:
        app: mern-mongodb
    spec:
      containers:
        - name: mern-mongodb
          image: iamsamitdev/mern_mongodb:1.0
          resources:
            limits:
              memory: "500Mi"
              cpu: "200m"
            requests:
              memory: "500Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: mern-mongodb
  namespace: demok8s
spec:
  type: ClusterIP
  selector:
    app: mern_mongodb
  ports:
    - port: 27010
      targetPort: 27010    
      