apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-react
  labels:
    app: react
  namespace: demok8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mern-react
  template:
    metadata:
      name: mern-react
      labels:  
        app : mern-react
    spec:
      containers:
        - name: mern-react
          image: iamsamitdev/mern_react:1.0
          resources:
            limits:
              memory: "500Mi"
              cpu: "200m"
            requests:
              memory: "500Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: mern-react
  namespace: demok8s
spec:
  type: ClusterIP
  selector:
    app: mern_react
  ports:
    - port: 80
      targetPort: 80